SMTG-Bham/sumo

setup.py
sumo/plotting/__init__.py
sumo/plotting/dos_plotter.py
tests/tests_plotting/test_dos_plotter.py

This addresses #8 by ensuring that orbital colours will be consistent across multiplots and between re-plot calls from an interactive notebook.
A dict  `sumo.plotting.colour_cache` is held at the plotting level (as other plots may wish to share this information) and initialised as `{}`; when the dos_plotter does not find an orbital colour specified in the ``colours`` argument it will take the next item from a cycle and update the cache with `{element: {orbital: colour}}`. To clear the cache and start the colour cycle from the beginning, this module-level variable can be manually reset to `{}`. This would rarely be necessary: I still recommend that any real colour tweaking should be done by passing a dict or config directly.
Tests are included and currently pass.

Cache DOS colours and re-use them

---

sumo/cli/bandplot.py
sumo/cli/dosplot.py
sumo/plotting/bs_plotter.py
sumo/plotting/dos_plotter.py

Addresses #9 by providing: `--xlabel` and `--ylabel` options for _dosplot_; `--ylabel` and `--dos-label` for _bandplot_.
`--dos-label` looks a bit cramped right next to the legend there, so I'm happy to leave `None` as the default. This seems most useful with `--total-only`, if only there was a way to disable the legend.

Axis labels

---

sumo/cli/phonon_bandplot.py
sumo/plotting/phonon_bs_plotter.py

Added a `--dos-file` option to `sumo-phonon-bandplot`, which expects a *total_dos.dat* from Phonopy. 
The colour is hard coded and the aspect ratio is not automatically corrected. 
Also, only total dos is plotted rather than partial DOS.

Finishing implementing DOS to sumo-phonon-bandplot

---

CHANGELOG.rst
sumo/cli/phonon_bandplot.py
sumo/plotting/phonon_bs_plotter.py

Added a `--dos-file` option to `sumo-phonon-bandplot`, which expects a _total_dos.dat_ from Phonopy.
The colour is hard coded and the aspect ratio is not automatically corrected.
Also, only total dos is plotted rather than partial DOS.
Implemented by @ajjackson and @zccaayo.

Implement combined phonon band structure and dos plotting

---

sumo/plotting/dos_plotter.py

This fixes an alignment issue with DOSes that caused them to not line up with Bandstructures when aligning to the Fermi-level
- Added zero_to_efermi to SDOSPlotter.dos_plot_data

Aligns DOS to Fermi level

---

sumo/cli/phonon_bandplot.py
sumo/plotting/phonon_bs_plotter.py

Address Issue #28 to add `--units` option to phonon DOS plotter. THz, cm-1, eV and meV are supported. Conversions are performed using the Phonopy unit conversion values. Options are case-insensitive where practical and assigned to correct case in y-axis label.

ENH: --units option for phonon band structures

---

.travis.yml

The build on Travis is getting pymatgen-related errors with Python 3.6 but not Python 3.5

WIP: Fix continuous integration

---

sumo/plotting/bs_plotter.py
tests/tests_plotting/test_band_plotter.py

Another "secret labels" feature to aid with use of custom k-point paths. High-symmetry points are handled in Pymatgen and Sumo as a dictionary of labels and positions. This means that it is prohibited to re-use the same label for a different k-point, even if that position is actually symmetry-equivalent or a periodic image in reciprocal space.
There are arguments for and against using such band structures, but here we provide a workaround for those who wish to re-use labels for non-equivalent points. By appending an '@' symbol to the label in
KPOINTS or syml.ext (i.e. 'X' becomes 'X@'), a new special point is identified which will also display as 'X' in the plotted band structure. What if you need another one? Just add more @ signs, the code uses regular expressions to look for a block of …

Enable repeat labels on band structure, made unique internally with trailing @

---

sumo/plotting/__init__.py
sumo/plotting/optics_plotter.py
sumo/plotting/sumo_base.mplstyle

In sumo-optplot default behavior rounded y-axis to an apparent float value. 
Format string changed from 'g' to 'f' to allow floating point.

Fix missing floating point on y-axis of optplots.

---

sumo/cli/phonon_bandplot.py
sumo/phonon/phonopy.py

Bugfix for #57 
The BORN file should contain a primitive cell, but Sumo was passing the full unit cell to Phonopy, leading to a mismatch in atom count (and, presumably, in coordinates...). The fix accesses an internal Phonopy attribute, which isn't ideal but seems the best option for internal consistency and minimal user input.
While fixing this, I also added support for the new(ish) Phonopy option `--primitive-axis=auto`, which may be accessed with `sumo-phonon-bandplot --primitive-auto`. A very welcome feature, this should make working with primitive cells less tedious.

Primitive cells in phonon-bandplot

---

setup.py

This should solve #62 by restricting the range of installed Pymatgen versions when installing Sumo under 3.5. We should do at least one point-release with this in place before dropping 3.5 support ourselves so that 3.5 users have a known working Sumo installer. We will however need to drop 3.5 when we use any new Pymatgen features.
Once this is in master I suggest that other pull requests rebase and force-push in order to get their CI working without adding a lot of merges to the history.

Restrict Pymatgen version for Python 3.5 installation

---

sumo/plotting/dos_plotter.py

A simple fix for #56 ; just calculate the cutoff as though the total-DOS is there.
It seems as good a way of defining the threshold as any other?

BUGFIX: set DOS cutoff when --no-total

---

sumo/cli/phonon_bandplot.py

User style arguments were not being passed correctly to the phonon dos plotter.

BUGFIX: styles not applied to phonon-bandplot from CLI

---

sumo/cli/phonon_bandplot.py
sumo/phonon/phonopy.py
sumo/plotting/phonon_bs_plotter.py
sumo/plotting/sumo_phonon.mplstyle
tests/tests_phonon/test_phonopy.py

Here's an attempt at #65 
So far we can dump a JSON of the Pymatgen object with `--to-json filename.json`, and select multiple of them to add to the plotting output with `--from-json bands-1.json bands-2.json ...`, . If no FORCE_SETS etc. is chosen but --from-json is set, then instead of looking for FORCE_SETS it will just plot the series of JSON files.
I tweaked the style file so the default green is a little darker and we get a green -> pale-blue sequence of up to four colours.
Todo:
- `--style` seems to be broken?
- Check the x-axis scaling is working correctly with some qha data. (If anyone has some lying around that would be great.)
- `--labels`

Phonon bandplot: JSON dumping/loading, overlaying plots

---

sumo/cli/bandplot.py
sumo/cli/dosplot.py
sumo/electronic_structure/bandstructure.py
sumo/plotting/bs_plotter.py
sumo/plotting/dos_plotter.py

I've added a 'spin' option to the CLI interface for _sumo-dosplot_ and _sumo-bandplot_, including _sumo-bandplot_ projected BS. The syntax is explained in the docstrings and help output: "spin (:obj:`str`, optional): Plot a spin-polarised band structure, "up" for spin up only, "down" for spin down only. Defaults to ``None``."  
I've checked that it works as it should.  
Examples:  
Spin-polarised DOS (Before Changes)  
Spin-polarised DOS, Spin Up Only (After Changes)  
Spin-polarised DOS, Spin Down Only (After Changes)  
Spin-Polarised BS (Before Changes)  
Spin-Polarised BS, Spin Down Only (After Changes)  
Spin-Polarised BS, Spin Up Only (After Changes)  
Spin-Polarised BS with Projections (Spin Down Only)(After Changes)  
Spin-Polarised BS with Projections (Spin Up Only)(After Changes)

Spin-Polarisation Selection Option 

---

sumo/cli/bandplot.py
sumo/cli/dosplot.py
sumo/electronic_structure/bandstructure.py

Following on from issue #94 , I've moved the `string_to_spin` function (which accepts the `--spin` argument and converts to a pymatgen Spin object) from the `parser.add_argument` call (in which it was implemented as the `type` parameter) to just before the `get_plot` calls in `dosplot` and `bandplot`. The `type` parameter in  `parser.add_argument` (for `dosplot` and `bandplot`) is now just `str`, so the conversion of the `spin` argument via the `string_to_spin` function now takes place just before the `get_plot` calls in `dosplot` and `bandplot`. This ensures that the `spin` argument is correctly parsed and converted for both cli usage and for Python API usage of `dosplot` and/or `bandplot` (as was the issue in this case). I've also made the `string_to_spin` function capable of accepting …

Move `string_to_spin` function for API compatibility

---

CHANGELOG.rst
sumo/cli/kgen.py
sumo/io/castep.py
tests/tests_io/test_castep.py

Bug reported in https://github.com/ajjackson/castep-sumo-tutorial/issues/1
The Castep implementation overlooked a block in kgen which writes a
primitive cell file when non-primitive input was provided. This should
be harder to overlook; consider implementing a more consistent
interface for additional codes?
Anyway, this PR adds a Structure importer to the CastepCell class in order to complete the required functionality. It's a bit inelegant.

BUGFIX: Write primitive cell from kgen when using CASTEP

---

sumo/cli/bandplot.py

Fix a bug reported by @jryates; when adding a DOS to a CASTEP band structure, the --ymin and --ymax values were not being passed to the DOS plotter. The results are not pretty:
Passing the options seems to clean this up:

Pass bandplot range to CASTEP DOS

---

CHANGELOG.rst
sumo/io/questaal.py

Presumably this was added for debugging, and accidentally included in a commit. My bad!
Error was reported by @badw 
The fact that this got through testing tells us that the testing could use some work! Still I'm inclined to push this out sooner rather than later, as currently Questaal band structures are broken in the PyPI release.
@utf is it ok if I do a quick merge and release for this?

Bugfix: remove spurious Exception from questaal band_structure

---

sumo/cli/optplot.py
sumo/plotting/optics_plotter.py

Add option to `sumo-optplot` to plot the absorption data as a function of wavelength in nanometres, as is commonly done experimentally.
Tested and all seems to behave as expected.
EG: `sumo-optplot --ymax 1.2e6 --units nm --xmax 2000 --xmin 300 -g 0.1 --bandgap 1.4` gives:
while `sumo-optplot --ymax 1.2e6 --xmax 4.13 --xmin 0.62 -g 0.1 -b 1.4` (same energy range) gives:

Add option to plot absorption data as a function of wavelength

---

sumo/cli/bandplot.py

I noticed that when plotting the DOS alongside the band structure with `sumo`, the DOS colours changed from what they were with `sumo-dosplot` (which can ofc be a bit annoying when putting these figures in SI for example, as colours aren't consistent), unless you explicitly pointed to the `orbital_colours.conf` file or used your own one.
From a bit of digging, I found that this came from a small typo in `bandplot.py`, fixed now! (This line now matches that in `dosplot.py`)

Fix colour parsing for BS + DOS plots

---

sumo/plotting/optics_plotter.py

Noticed this typo when getting some absorption plots with sumo, where the CLI-specified xmax would be overridden by the automatic value. Tested and fixes the issue.

Fix xmax typo in optics_plotter

---

CHANGELOG.rst
sumo/cli/bandstats.py
sumo/electronic_structure/bandstructure.py

The pymatgen logic for extracting branches in the band structure requires duplicating the high-symmetry points. To avoid wasting compute resources on these extra points, sumo-bandplot/bandstats adds this points dynamically rather than including them in the DFT calculation.
However, this means `sumo-bandstats` reports the wrong indices for the VBM and CBM with respect to the band structure calculation. This PR fixes this behaviour.
Fixes: #167

Fix k-point indicies in sumo-bandstats

---

docs/src/customising-plots.rst

Closes #177 
This link in the docs pointed to a branch which has now been deleted.

Fix Github blob link to use master branch

---

sumo/cli/bandplot.py
sumo/plotting/bs_plotter.py

Fixes #180 
Changed the defaults of colour1, colour2 and colour3 from red, green, blue to red, blue, green to make it easier to reproduce the expected behaviour with 2 colours.

Fix projected band plot with 2 colour

---

sumo/plotting/__init__.py
sumo/plotting/optics_plotter.py

Example of old optplot output:
Example of fixed output:

Fix optplot superscript

---

sumo/plotting/bs_plotter.py
sumo/plotting/sumo_bs.mplstyle

Raised in #192 ; how can users adjust the size of VBM/CBM markers? This is currently hard-coded but does not need to be.
The CBM/VBM edge markers are plotted with `scatter`, which has a default marker size of s = rcParams['lines.markersize'] ** 2.
Our hard-coded `s=100` is rather chunky, so by replacing this with an equivalent value in the style file we allow users to customize it.

Set band-edge marker size in style file

---

.github/workflows/docs.yml
.github/workflows/tests.yml
setup.py
sumo/cli/bandplot.py
sumo/cli/dosplot.py
sumo/plotting/__init__.py
sumo/symmetry/brad_crack_kpath.py
tests/tests_electronic_structure/test_optics.py
tests/tests_io/test_castep.py
tests/tests_io/test_questaal.py
tests/tests_phonon/test_phonopy.py
tests/tests_plotting/test_dos_plotter.py
tests/tests_symmetry/test_bradcrack_kpath.py
tests/tests_symmetry/test_custom_kpath.py
tests/tests_symmetry/test_pymatgen_kpath.py
tests/tests_symmetry/test_seekpath_kpath.py

Hi again, 
This PR moves sumo from using `pkg_resources` to `importlib.resources`, which fixes the failing tests. Note that `pkg_resources` is now [deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html) and the devs recommend migrating to `importlib.resources` or the `importlib-resources` backport for older versions of python.
**Changelog**:
* Replace `pkg_resources` with `importlib.resources` for python 3.9+ and the `importlib_resources` backport for python 3.8. This fixes the issue of failing tests.
* Turn `tests` into its own package for easier use with `importlib.resources.files`, and add proper exclusion to `setup.py`
* Update both the tests and docs workflows to use more up-to-date actions, thus eliminating the deprecation warnings and simplifying the caching action.
* …

Fix failing tests and migrate to importlib

---

sumo/cli/bandplot.py
sumo/plotting/bs_plotter.py
sumo/plotting/sumo_base.mplstyle

Hi Sumo devs,
I'm a physics PhD student at UC Berkeley/Berkeley Lab working with Dr. Sinéad Griffin. Sumo is one of my favorite tools and I use it quite heavily, so I would love to contribute.
This very simple PR adds a "title" feature to band plots,  including the new `--title` flag of `sumo-bandplot` and `title` argument of `SBSPlotter.get_plot` and `SBSPlotter.get_projected_plot`. I've found this extremely helpful when, for example, looking at the changes in the electronic structure as you distort or displace atoms-- it's quite helpful for making high quality GIFs for presentations.
Example:
Example GIF showing the effect of phonons of different amplitudes on Sr3PbO:
I have not implemented titles for the other types of plots (DOS, optics, phonons), but it's quite easy to do and I'll …

Add support for band structure titles

---

sumo/plotting/__init__.py
sumo/plotting/bs_plotter.py

Hi @utf and @ajjackson!
This is a tiny update to allow the user to pass `kwargs` to `draw_themed_line`. The main reason is so that we can control `zorder` when importing and using this function, if the band plot is e.g. actually a colourmap, in which case the default `zorder=0` hides the zero line, but bumping it up shows it. 
This is because I'm using `sumo` to add co - DOS plot functionality (like `sumo-bandplot`) to the unfolded bandstructure plotting in [`easyunfold`](https://smtg-ucl.github.io/easyunfold/), so using some of these useful functions! 🙌
Work in progress, but like this:

Add `**kwargs` to `draw_themed_line`

---

sumo/electronic_structure/optics.py

Checked the code with `ruff check . --select NPY201` and this was the only required change.
```
~/s/sumo (numpy-fix)> ruff check . --select NPY201                                 (science)
sumo/electronic_structure/optics.py:259:54: NPY201 [*] `np.complex_` will be removed in NumPy 2.0. Use `numpy.complex128` instead.
Found 1 error.
[*] 1 fixable with the `--fix` option.
```

Numpy 2.0 compatibility tweak

---

CHANGELOG.rst
sumo/cli/dosplot.py
sumo/cli/optplot.py

Just noticed that the docstring for `zero-energy` in `sumo-dosplot` was incorrect (duplication of `zero-line` which has different behaviour), so just a small update

Small docstring fix for `sumo-dosplot`

---

CHANGELOG.rst
sumo/electronic_structure/dos.py
tests/tests_electronic_structure/test_dos.py

Since https://github.com/materialsproject/pymatgen/pull/4239, `Spin.down` entries are no longer stored in `pymatgen` DOS objects parsed from SOC calculations (as desired). There was a patch in `sumo` to delete this entry for SOC calculations if present, to make later downstream plotting easier, but this now causes a `KeyError` when used with the latest `pymatgen` due to this entry no longer being present:
```
sumo-dosplot
Traceback (most recent call last):
File "/home/mmm0650/miniconda3/bin/sumo-dosplot", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/mmm0650/miniconda3/lib/python3.12/site-packages/sumo/cli/dosplot.py", line 646, in main
dosplot(
File "/home/mmm0650/miniconda3/lib/python3.12/site-packages/sumo/cli/dosplot.py", line 207, in dosplot
dos, pdos = load_dos(
^^^^^^^^^ …
```

Fix SOC DOS parsing for latest `pymatgen`
